
server:
  port: 9581   

spring:
  application:
    name: edgeserver  
  
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/  
      
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    productlobaservice:
      path: /pd/**
      serviceId: PRODUCTLOBASERVICE
    shoppingcartlobaservice:
      path: /sc/**
      serviceId: SHOPPINGCARTLOBASERVICE
    orderlobaservice:
      path: /od/**
      serviceId: ORDERLOBASERVICE  
            