spring:
  application:
    name: shoppingcartservice

  kafka:
    bootstrap-servers: localhost:9095
    
    
  data:
    mongodb:
      database: ecommdb
      port: 27017
      host: localhost
  
server:
  port: 8582   
      
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/  
      
mongodb:
  events:
    collection:
      name: events
    snapshot:
      collection:
        name: snapshots

      